import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavbarPage from "@/Components/navbar/navbar";
import Footer from "@/Components/footer/footer";
import Home from "./page";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <NavbarPage />
        <div className="bg-white">
        <main className="mx-auto max-w-xl">
        <div className=" px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
          <Home />
        {children}
        </div>
        </main> 
        <Footer />
        </div>
      </body>
    </html>
  );
}
